### ISSUE TITLE
use yaml arrays for peers

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-http-gw#157]
https://github.com/nspcc-dev/neofs-http-gw/blob/97cde6e2628bf8c6f6df7bf0895d67be2fb29b98/config/config.yaml#L19-L38

`peers` is an associative array with `0`, `1`, `2`  keys.
I'd prefer to see an array here:
```yaml
peers:
  - address: grpc://s01.neofs.devenv:8080
    priority: 1
    weight: 1
  - address: grpc://s02.neofs.devenv:8080
    priority: 2
    weight: 1
  - address: grpc://s03.neofs.devenv:8080
    priority: 2
    weight: 9
```
